name: SalxAET
version: 1.0-SNAPSHOT
main: com.legacy.salxaet.LAnticheat
api-version: '1.21'
author: LegacyNetwork
description: LegacyNetwork Ozel Gelismis AntiCheat Eklentisi
depend: [ProtocolLib]

commands:
  salxaet:
    description: SalxAET ana komutu.
    permission: salxaet.admin
    usage: /<command>
    
